import React, { useEffect } from 'react';
import {
  Trophy,
  RotateCcw,
  Share2,
  Download,
  CheckCircle2,
  AlertTriangle,
  Zap,
  Activity,
  Target,
  Clock,
  Sparkles,
  ArrowRight,
  Award,
  BookOpen
} from 'lucide-react';
import { ResponsiveContainer, LineChart, Line, XAxis, YAxis, Tooltip, CartesianGrid } from 'recharts';
import confetti from 'canvas-confetti';
import { TestResult } from '../types';

interface ResultModalProps {
  result: TestResult;
  onRetry: () => void;
  onNewTest: () => void;
  onLaunchTargetedPractice: (weakChars: string[]) => void;
  onNavigateToImprovement?: () => void;
  isPersonalBest: boolean;
}

export const ResultModal: React.FC<ResultModalProps> = ({
  result,
  onRetry,
  onNewTest,
  onLaunchTargetedPractice,
  onNavigateToImprovement,
  isPersonalBest
}) => {
  // Fire confetti if personal best or Lok Sewa full marks!
  useEffect(() => {
    if (isPersonalBest || (result.isLokSewaMode && (result.lokSewaMarks || 0) >= 2.5)) {
      confetti({
        particleCount: 100,
        spread: 70,
        origin: { y: 0.6 }
      });
    }
  }, [isPersonalBest, result.isLokSewaMode, result.lokSewaMarks]);

  // Extract top mistyped words/characters
  const mistypedWords = Object.entries(result.mistypedWordsMap || {})
    .sort((a, b) => Number(b[1]) - Number(a[1]))
    .slice(0, 5);

  const weakCharacters = mistypedWords.flatMap(([word]) => word.split('')).slice(0, 6);

  // Download PDF / Printable HTML summary report
  const handleDownloadResult = () => {
    const isLokSewa = result.isLokSewaMode;
    const reportText = `===========================================
${isLokSewa ? 'LOK SEWA AAYOG IT SKILL TEST - SCORECARD' : 'NEPALI TYPING PRO - PERFORMANCE REPORT'}
===========================================
Date: ${new Date(result.timestamp).toLocaleString()}
Language Mode: ${result.language.toUpperCase()}
Test Mode: ${result.testType} (${result.durationSeconds}s)
${isLokSewa ? `\nLOK SEWA OFFICIAL EVALUATION:
-------------------------------------------
Correct Words Per Minute (CWPM): ${result.lokSewaCwpm ?? result.netWpm} CWPM
Lok Sewa Skill Marks: ${(result.lokSewaMarks ?? 0).toFixed(2)} / 2.50
Status: ${(result.lokSewaMarks ?? 0) >= 2.5 ? 'Full Marks Achieved' : (result.lokSewaMarks ?? 0) >= 1.0 ? 'Passed' : 'Needs Practice'}
Total Words Typed: ${result.totalWordsTyped}
Wrong Words (Deducted): ${result.wrongWords}
Correct Words: ${result.correctWords}
Evaluation Formula: (${result.totalWordsTyped} - ${result.wrongWords}) ÷ 5 = ${result.lokSewaCwpm ?? result.netWpm} CWPM\n` : ''}
SPEED & ACCURACY METRICS:
-------------------------------------------
Net WPM: ${result.netWpm} WPM
Gross WPM: ${result.grossWpm} WPM
Accuracy: ${result.accuracy}%
Consistency: ${result.consistencyPercent}%
Rating: ${result.performanceGrade}

DETAILED BREAKDOWN:
-------------------------------------------
Total Characters Typed: ${result.totalCharactersTyped}
Correct Characters: ${result.correctCharacters}
Wrong Characters: ${result.wrongCharacters}
Correct Words: ${result.correctWords}
Wrong Words: ${result.wrongWords}
Mistakes Count: ${result.mistakesCount}
Backspaces Used: ${result.backspacesCount}
Time Elapsed: ${result.elapsedSeconds} seconds

MOST MISTYPED WORDS:
${mistypedWords.length > 0 ? mistypedWords.map(([w, c]) => `- ${w}: ${c} mistakes`).join('\n') : 'None! Great accuracy!'}

===========================================
Generated by Nepali Typing Pro
https://nepalitypingpro.app
===========================================`;

    const blob = new Blob([reportText], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = isLokSewa
      ? `LokSewa_Typing_Scorecard_${result.lokSewaCwpm || result.netWpm}CWPM_${Date.now()}.txt`
      : `Nepali_Typing_Result_${result.netWpm}WPM_${Date.now()}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  // Copy result text to clipboard
  const handleShareResult = () => {
    const isLokSewa = result.isLokSewaMode;
    const text = isLokSewa
      ? `🇳🇵 Lok Sewa IT Skill Test Result: I scored ${(result.lokSewaMarks ?? 0).toFixed(2)}/2.50 with ${result.lokSewaCwpm ?? result.netWpm} Correct WPM in ${result.language === 'nepali' ? 'Nepali' : 'English'} on Nepali Typing Pro! 🚀`
      : `🇳🇵 I just typed ${result.netWpm} WPM with ${result.accuracy}% accuracy in Romanized Nepali on Nepali Typing Pro! 🚀 Test your typing speed at https://nepalitypingpro.app`;
    navigator.clipboard.writeText(text);
    alert('Result summary copied to clipboard!');
  };

  return (
    <div id="result-screen-modal" className="w-full bg-white dark:bg-slate-900 rounded-3xl border border-slate-200 dark:border-slate-800 shadow-xl p-6 sm:p-10 my-6 transition-all animate-fadeIn">
      
      {/* Header Banner */}
      <div className="flex flex-wrap items-center justify-between gap-4 border-b border-slate-100 dark:border-slate-800 pb-6 mb-8">
        <div>
          <div className="flex flex-wrap items-center gap-3">
            {result.isLokSewaMode ? (
              <span className="flex items-center gap-1.5 px-3 py-1 bg-rose-100 dark:bg-rose-950 text-rose-800 dark:text-rose-300 font-extrabold text-xs rounded-full border border-rose-300 dark:border-rose-800">
                <Award className="w-4 h-4 text-rose-600" /> Lok Sewa Exam Evaluation
              </span>
            ) : isPersonalBest ? (
              <span className="flex items-center gap-1 px-3 py-1 bg-amber-100 dark:bg-amber-900/60 text-amber-800 dark:text-amber-300 font-extrabold text-xs rounded-full border border-amber-300">
                <Trophy className="w-4 h-4 text-amber-500 fill-amber-500" /> New Personal Best!
              </span>
            ) : null}
            <span className={`px-3 py-1 font-bold text-xs rounded-full ${
              result.performanceGrade === 'Excellent'
                ? 'bg-emerald-100 dark:bg-emerald-950 text-emerald-800 dark:text-emerald-300'
                : result.performanceGrade === 'Good'
                ? 'bg-blue-100 dark:bg-blue-950 text-blue-800 dark:text-blue-300'
                : 'bg-amber-100 dark:bg-amber-950 text-amber-800 dark:text-amber-300'
            }`}>
              Rating: {result.performanceGrade}
            </span>
          </div>
          <h2 className="text-2xl sm:text-3xl font-extrabold text-slate-900 dark:text-slate-100 tracking-tight mt-2">
            {result.isLokSewaMode ? 'Lok Sewa IT Skill Test Result' : 'Typing Test Completed'}
          </h2>
          <p className="text-xs sm:text-sm text-slate-500 dark:text-slate-400 mt-0.5">
            {result.language === 'nepali' ? 'Devanagari / Romanized Nepali Unicode' : 'English Touch Typing'} • {new Date(result.timestamp).toLocaleTimeString()}
          </p>
        </div>

        {/* Action Buttons */}
        <div className="flex items-center gap-2">
          <button
            onClick={onRetry}
            className="flex items-center gap-2 px-5 py-2.5 rounded-xl bg-blue-600 hover:bg-blue-700 text-white font-bold text-sm shadow-md shadow-blue-500/20 transition-all cursor-pointer"
          >
            <RotateCcw className="w-4 h-4" />
            <span>Retry (Ctrl+Enter)</span>
          </button>
          <button
            onClick={onNewTest}
            className="flex items-center gap-2 px-4 py-2.5 rounded-xl bg-slate-100 dark:bg-slate-800 hover:bg-slate-200 dark:hover:bg-slate-700 text-slate-700 dark:text-slate-200 font-bold text-sm transition-all cursor-pointer"
          >
            <span>New Test</span>
          </button>
        </div>
      </div>

      {/* Official Lok Sewa Scorecard (When in Lok Sewa Mode) */}
      {result.isLokSewaMode && (
        <div className="bg-gradient-to-r from-rose-500/10 via-indigo-500/10 to-amber-500/10 dark:from-rose-950/40 dark:via-indigo-950/40 dark:to-amber-950/40 p-6 rounded-3xl border border-rose-200 dark:border-rose-800/80 mb-8 space-y-4">
          <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 border-b border-rose-200/60 dark:border-rose-800/40 pb-3">
            <div className="flex items-center gap-2">
              <Award className="w-6 h-6 text-rose-600 dark:text-rose-400" />
              <div>
                <h3 className="text-base font-black text-slate-900 dark:text-slate-100">
                  Lok Sewa Aayog IT Skill Test • Scorecard
                </h3>
                <p className="text-xs text-slate-500 dark:text-slate-400">
                  Evaluated with 5-minute standard formula: CWPM = (Total Words Typed − Wrong Words) ÷ 5
                </p>
              </div>
            </div>
            <div className="text-right">
              <span className={`px-3 py-1 rounded-full text-xs font-black ${
                (result.lokSewaMarks ?? 0) >= 2.5
                  ? 'bg-emerald-500 text-white shadow-xs'
                  : (result.lokSewaMarks ?? 0) >= 1.0
                  ? 'bg-blue-600 text-white'
                  : 'bg-rose-600 text-white'
              }`}>
                {(result.lokSewaMarks ?? 0) >= 2.5
                  ? 'FULL MARKS (2.5/2.5)'
                  : (result.lokSewaMarks ?? 0) >= 1.0
                  ? 'PASSED'
                  : 'NEEDS IMPROVEMENT'}
              </span>
            </div>
          </div>

          <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
            <div className="bg-white/90 dark:bg-slate-900/90 p-4 rounded-2xl border border-slate-200 dark:border-slate-800 text-center">
              <span className="text-[10px] font-extrabold uppercase tracking-wider text-slate-400">Correct WPM (CWPM)</span>
              <div className="text-3xl font-black text-rose-600 dark:text-rose-400 font-mono mt-1">
                {result.lokSewaCwpm ?? result.netWpm}
              </div>
              <span className="text-[10px] text-slate-500 font-bold">
                {result.language === 'nepali' ? 'Target: 25+ CWPM' : 'Target: 30+ CWPM'}
              </span>
            </div>

            <div className="bg-white/90 dark:bg-slate-900/90 p-4 rounded-2xl border border-slate-200 dark:border-slate-800 text-center">
              <span className="text-[10px] font-extrabold uppercase tracking-wider text-slate-400">Obtained Marks</span>
              <div className="text-3xl font-black text-indigo-600 dark:text-indigo-400 font-mono mt-1">
                {(result.lokSewaMarks ?? 0).toFixed(2)}
              </div>
              <span className="text-[10px] text-slate-500 font-bold">
                Out of 2.50 Marks
              </span>
            </div>

            <div className="bg-white/90 dark:bg-slate-900/90 p-4 rounded-2xl border border-slate-200 dark:border-slate-800 text-center">
              <span className="text-[10px] font-extrabold uppercase tracking-wider text-slate-400">Total Words Typed</span>
              <div className="text-2xl font-black text-slate-800 dark:text-slate-200 font-mono mt-1">
                {result.totalWordsTyped}
              </div>
              <span className="text-[10px] text-slate-500">
                {result.correctWords} correct words
              </span>
            </div>

            <div className="bg-white/90 dark:bg-slate-900/90 p-4 rounded-2xl border border-slate-200 dark:border-slate-800 text-center">
              <span className="text-[10px] font-extrabold uppercase tracking-wider text-slate-400">Wrong Words (Deducted)</span>
              <div className="text-2xl font-black text-rose-600 dark:text-rose-400 font-mono mt-1">
                {result.wrongWords}
              </div>
              <span className="text-[10px] text-rose-500 font-bold">
                Deducted from Total
              </span>
            </div>
          </div>
        </div>
      )}

      {/* Hero Stats Grid */}
      <div className="grid grid-cols-2 lg:grid-cols-4 gap-4 mb-8">
        
        {/* Net WPM */}
        <div className="bg-gradient-to-br from-blue-50 to-indigo-50/50 dark:from-blue-950/40 dark:to-indigo-950/30 p-6 rounded-2xl border border-blue-200/80 dark:border-blue-800/80 flex flex-col justify-between">
          <div className="flex items-center justify-between">
            <span className="text-xs font-bold uppercase tracking-wider text-blue-600 dark:text-blue-400">Net Speed</span>
            <Zap className="w-5 h-5 text-blue-600 dark:text-blue-400" />
          </div>
          <div className="my-3">
            <div className="text-4xl sm:text-5xl font-black text-blue-600 dark:text-blue-300 tracking-tight leading-none">
              {result.netWpm}
            </div>
            <div className="text-xs font-semibold text-blue-700 dark:text-blue-400 mt-1">
              Words Per Minute
            </div>
          </div>
          <div className="text-[11px] text-slate-500 dark:text-slate-400 font-medium">
            Gross WPM: <strong>{result.grossWpm}</strong>
          </div>
        </div>

        {/* Accuracy */}
        <div className="bg-gradient-to-br from-emerald-50 to-teal-50/50 dark:from-emerald-950/40 dark:to-teal-950/30 p-6 rounded-2xl border border-emerald-200/80 dark:border-emerald-800/80 flex flex-col justify-between">
          <div className="flex items-center justify-between">
            <span className="text-xs font-bold uppercase tracking-wider text-emerald-600 dark:text-emerald-400">Final Accuracy</span>
            <Target className="w-5 h-5 text-emerald-600 dark:text-emerald-400" />
          </div>
          <div className="my-3">
            <div className="text-4xl sm:text-5xl font-black text-emerald-600 dark:text-emerald-300 tracking-tight leading-none">
              {result.accuracy}%
            </div>
            <div className="text-xs font-semibold text-emerald-700 dark:text-emerald-400 mt-1">
              Submitted Text Precision
            </div>
          </div>
          <div className="text-[11px] text-slate-500 dark:text-slate-400 font-medium flex items-center justify-between">
            <span>Mistakes Made: <strong className="text-rose-600 dark:text-rose-400">{result.mistakesCount}</strong></span>
            {result.backspacesCount > 0 && (
              <span className="text-emerald-600 dark:text-emerald-400 font-bold">Corrected via Backspace</span>
            )}
          </div>
        </div>

        {/* Consistency */}
        <div className="bg-gradient-to-br from-purple-50 to-violet-50/50 dark:from-purple-950/40 dark:to-violet-950/30 p-6 rounded-2xl border border-purple-200/80 dark:border-purple-800/80 flex flex-col justify-between">
          <div className="flex items-center justify-between">
            <span className="text-xs font-bold uppercase tracking-wider text-purple-600 dark:text-purple-400">Consistency</span>
            <Activity className="w-5 h-5 text-purple-600 dark:text-purple-400" />
          </div>
          <div className="my-3">
            <div className="text-4xl sm:text-5xl font-black text-purple-600 dark:text-purple-300 tracking-tight leading-none">
              {result.consistencyPercent}%
            </div>
            <div className="text-xs font-semibold text-purple-700 dark:text-purple-400 mt-1">
              Rhythm Stability
            </div>
          </div>
          <div className="text-[11px] text-slate-500 dark:text-slate-400 font-medium">
            Time Taken: <strong>{result.elapsedSeconds}s</strong>
          </div>
        </div>

        {/* Characters Breakdown */}
        <div className="bg-gradient-to-br from-slate-50 to-slate-100 dark:from-slate-800 dark:to-slate-800/60 p-6 rounded-2xl border border-slate-200 dark:border-slate-700 flex flex-col justify-between">
          <div className="flex items-center justify-between">
            <span className="text-xs font-bold uppercase tracking-wider text-slate-600 dark:text-slate-300">Characters</span>
            <Clock className="w-5 h-5 text-slate-500" />
          </div>
          <div className="my-3">
            <div className="text-4xl sm:text-5xl font-black text-slate-800 dark:text-slate-100 tracking-tight leading-none">
              {result.totalCharactersTyped}
            </div>
            <div className="text-xs font-semibold text-slate-600 dark:text-slate-400 mt-1">
              Total Keystrokes
            </div>
          </div>
          <div className="flex items-center justify-between text-[11px] text-slate-500 dark:text-slate-400 font-medium">
            <span>Correct: <strong className="text-emerald-600 dark:text-emerald-400">{result.correctCharacters}</strong></span>
            <span>Wrong: <strong className="text-rose-600 dark:text-rose-400">{result.wrongCharacters}</strong></span>
          </div>
        </div>

      </div>

      {/* Speed & Accuracy Over Time Chart */}
      <div className="w-full bg-slate-50 dark:bg-slate-800/50 p-6 rounded-2xl border border-slate-200/80 dark:border-slate-700/80 mb-8">
        <div className="flex items-center justify-between mb-4">
          <h3 className="font-extrabold text-slate-800 dark:text-slate-200 text-base">
            Typing Speed Progress Graph (WPM over Time)
          </h3>
          <div className="flex items-center gap-3 text-xs font-medium">
            <span className="flex items-center gap-1.5"><span className="w-3 h-3 rounded-full bg-blue-600"></span> Net WPM</span>
            <span className="flex items-center gap-1.5"><span className="w-3 h-3 rounded-full bg-indigo-300"></span> Raw WPM</span>
          </div>
        </div>

        <div className="h-64 w-full">
          <ResponsiveContainer width="100%" height="100%">
            <LineChart data={result.wpmOverTime}>
              <CartesianGrid strokeDasharray="3 3" stroke="#e2e8f0" />
              <XAxis dataKey="second" unit="s" stroke="#94a3b8" />
              <YAxis stroke="#94a3b8" />
              <Tooltip />
              <Line type="monotone" dataKey="wpm" name="Net WPM" stroke="#2563eb" strokeWidth={3} dot={false} />
              <Line type="monotone" dataKey="rawWpm" name="Raw WPM" stroke="#a5b4fc" strokeWidth={2} strokeDasharray="4 4" dot={false} />
            </LineChart>
          </ResponsiveContainer>
        </div>
      </div>

      {/* Error Analysis & Personalized Recommendation Box */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mb-8">
        
        {/* Most Mistyped Words */}
        <div className="bg-white dark:bg-slate-800 p-6 rounded-2xl border border-slate-200 dark:border-slate-700 shadow-sm">
          <div className="flex items-center justify-between mb-3">
            <h4 className="font-extrabold text-slate-800 dark:text-slate-200 text-sm flex items-center gap-2">
              <AlertTriangle className="w-4 h-4 text-amber-500" />
              <span>Mistyped Words & Corrections</span>
            </h4>
            <span className="text-[11px] font-semibold text-slate-400">
              Recorded during typing
            </span>
          </div>

          {result.wordErrors && result.wordErrors.length > 0 ? (
            <div className="space-y-2 max-h-60 overflow-y-auto pr-1">
              {result.wordErrors.map((err, i) => (
                <div key={i} className="flex items-center justify-between p-2.5 rounded-xl bg-slate-50 dark:bg-slate-700/50 text-xs">
                  <div className="flex items-center gap-2">
                    <span className="font-bold text-slate-900 dark:text-slate-100 font-nepali text-sm">
                      {err.targetWord}
                    </span>
                    {err.typedWord && err.typedWord !== err.targetWord && (
                      <span className="text-rose-500 font-semibold font-nepali">
                        (typed: {err.typedWord})
                      </span>
                    )}
                  </div>
                  <div className="flex items-center gap-1.5">
                    {err.corrected ? (
                      <span className="px-2 py-0.5 rounded-md bg-emerald-100 dark:bg-emerald-950 text-emerald-700 dark:text-emerald-300 font-extrabold text-[10px] flex items-center gap-1">
                        <CheckCircle2 className="w-3 h-3" /> Corrected (Backspace)
                      </span>
                    ) : (
                      <span className="px-2 py-0.5 rounded-md bg-rose-100 dark:bg-rose-950 text-rose-700 dark:text-rose-300 font-extrabold text-[10px]">
                        Uncorrected
                      </span>
                    )}
                    <span className="text-xs font-bold text-rose-600 dark:text-rose-400 bg-rose-100 dark:bg-rose-950 px-2 py-0.5 rounded-md">
                      {err.mistakes}x
                    </span>
                  </div>
                </div>
              ))}
            </div>
          ) : mistypedWords.length > 0 ? (
            <div className="space-y-2">
              {mistypedWords.map(([word, count], i) => (
                <div key={i} className="flex items-center justify-between p-2.5 rounded-xl bg-slate-50 dark:bg-slate-700/50 text-sm">
                  <span
                    className="font-semibold text-slate-800 dark:text-slate-200 nepali-font-apply"
                    style={{ fontFamily: 'var(--app-nepali-font)' }}
                  >
                    {word}
                  </span>
                  <span className="text-xs font-bold text-rose-600 dark:text-rose-400 bg-rose-100 dark:bg-rose-950 px-2 py-0.5 rounded-md">
                    {count} mistakes
                  </span>
                </div>
              ))}
            </div>
          ) : (
            <div className="flex items-center gap-2 text-emerald-600 dark:text-emerald-400 font-semibold text-sm">
              <CheckCircle2 className="w-5 h-5" />
              <span>Perfect! Zero word mistakes detected in this test.</span>
            </div>
          )}
        </div>

        {/* Personalized Recommendations & Targeted Practice Callout */}
        <div className="bg-gradient-to-br from-indigo-50 to-blue-50 dark:from-indigo-950/50 dark:to-blue-950/40 p-6 rounded-2xl border border-indigo-200/80 dark:border-indigo-800/80 flex flex-col justify-between">
          <div>
            <h4 className="font-extrabold text-indigo-900 dark:text-indigo-200 text-sm flex items-center gap-2 mb-2">
              <Sparkles className="w-4 h-4 text-indigo-600 dark:text-indigo-400" />
              Personalized Recommendations
            </h4>
            <p className="text-xs text-slate-600 dark:text-slate-300 leading-relaxed mb-4">
              {result.accuracy < 90
                ? 'Your typing accuracy is below 90%. Focus on slowing down slightly to build muscle memory on tricky conjunct characters before building top speed.'
                : 'Great accuracy! Work on rhythm consistency to push your speed beyond ' + (result.netWpm + 10) + ' WPM.'}
            </p>
          </div>

          <div className="flex flex-col sm:flex-row gap-2 mt-3">
            {weakCharacters.length > 0 && (
              <button
                onClick={() => onLaunchTargetedPractice(weakCharacters)}
                className="flex-1 flex items-center justify-center gap-2 px-4 py-2.5 rounded-xl bg-indigo-600 hover:bg-indigo-700 text-white font-bold text-xs shadow-md transition-all cursor-pointer"
              >
                <span>Practice Weak Characters ({weakCharacters.slice(0, 3).join(', ')})</span>
                <ArrowRight className="w-4 h-4" />
              </button>
            )}

            {onNavigateToImprovement && (
              <button
                onClick={onNavigateToImprovement}
                className="flex-1 flex items-center justify-center gap-2 px-4 py-2.5 rounded-xl bg-amber-500 hover:bg-amber-400 text-slate-950 font-black text-xs shadow-md transition-all cursor-pointer"
              >
                <Zap className="w-4 h-4 fill-slate-950" />
                <span>Improve My Typing (AI Coach)</span>
              </button>
            )}
          </div>
        </div>

      </div>

      {/* Export & Share Footer */}
      <div className="flex flex-wrap items-center justify-between gap-4 pt-6 border-t border-slate-100 dark:border-slate-800 text-xs">
        <div className="flex items-center gap-2">
          <button
            onClick={handleDownloadResult}
            className="flex items-center gap-1.5 px-4 py-2 rounded-xl border border-slate-200 dark:border-slate-700 hover:bg-slate-50 dark:hover:bg-slate-800 text-slate-700 dark:text-slate-300 font-bold transition-all cursor-pointer"
          >
            <Download className="w-4 h-4 text-blue-600" />
            <span>Download Result (TXT / PDF)</span>
          </button>
          <button
            onClick={handleShareResult}
            className="flex items-center gap-1.5 px-4 py-2 rounded-xl border border-slate-200 dark:border-slate-700 hover:bg-slate-50 dark:hover:bg-slate-800 text-slate-700 dark:text-slate-300 font-bold transition-all cursor-pointer"
          >
            <Share2 className="w-4 h-4 text-emerald-600" />
            <span>Share Result</span>
          </button>
        </div>

        <div className="text-slate-500 dark:text-slate-400 font-medium">
          Saved automatically to local history.
        </div>
      </div>

    </div>
  );
};
